### ISSUE TITLE
Hard to understand errors when enabling Network Helper for linode/containerlinux

### ISSUE THREAD

**Issue by gerhard** [terraform-providers/terraform-provider-linode#23]
Enabling the Network Helper for linode/containerlinux image results in difficult to understand errors, e.g.:

```
linode_instance.2019: "authorized_users": conflicts with config
linode_instance.2019: "config": conflicts with image
linode_instance.2019: "image": conflicts with config
```

According to the [Use CoreOS Container Linux on Linode](https://www.linode.com/docs/applications/containers/use-coreos-container-linux-on-linode/) guide, _Network Helper is not compatible_ [with CoreOS]. Would it make sense to fail with a more helpful error?

```
linode_instance.2019: "config.network": incompatible with image
```

### Terraform Version

v0.11.10

### Affected Resource(s)

- linode\_instance v1.3.0

### Terraform Configuration Files
```hcl
data "linode_image" "changelog" {
  id = "linode/containerlinux"
}

resource "linode_instance" "2019" {
  # ... elided for brevity
  image = "${data.linode_image.changelog.id}"
  private_ip = true

  config {
    network = true
  }
}
```

### Debug Output

```
2019/01/02 12:34:39 [INFO] Terraform version: 0.11.10  
2019/01/02 12:34:39 [INFO] Go runtime version: go1.11.1
2019/01/02 12:34:39 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.10/bin/terraform", "plan"}
2019/01/02 12:34:39 [DEBUG] found provider "terraform-provider-linode_v1.3.0_x4"
2019/01/02 12:34:39 [DEBUG] found provider "terraform-provider-null_v1.0.0_x4"
2019/01/02 12:34:39 [DEBUG] found provider "terraform-provider-template_v1.0.0_x4"

# ... elided for brevity

linode_instance.2019 - *terraform.NodeValidatableResourceInstance
2019/01/02 12:34:39 [DEBUG] ReferenceTransformer: "linode_instance.2019" references: []
2019/01/02 12:34:39 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: ["config": conflicts with image "authorized_users": conflicts with config "image": conflicts with config]
2019/01/02 12:34:39 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: ["config": conflicts with image "authorized_users": conflicts with config "image": conflicts with config]
2019/01/02 12:34:39 [TRACE] [walkValidate] Exiting eval tree: linode_instance.2019
2019/01/02 12:34:39 [DEBUG] Attaching resource state to "linode_volume.db": &terraform.ResourceState{Type:"linode_volume", Dependencies:[]string{}, Primary:(*terraform.InstanceState)(0xc000411130), Deposed:[]*terraform.InstanceState{}, Provider:"provider.linode", mu:sync.Mutex{state:0, sema:0x0}}
2019/01/02 12:34:39 [TRACE] Graph after step *terraform.AttachStateTransformer:

# ... elided for brevity

linode_instance.2019: "authorized_users": conflicts with config
linode_instance.2019: "config": conflicts with image
linode_instance.2019: "image": conflicts with config
```

**Comment by displague** [comment]
@gerhard, thanks for the report!

I think the error message you are encountering is about `linode_instance` simple vs complex supported fields.  I'll address the idea of error messages specific to Network Helper + Container Linux first.

Neither Terraform, nor the API, currently report an error if Network Helper is enabled with a Container Linux image.  I'll raise that to the API team.  Regardless of API changes, I could see early validation for that being added to Terraform.

Perhaps the API image list could return whether an image supported network helper and then the Linode Terraform provider could just expose that through the images data resource.  

Having the API detect and error when network helper is enabled for a disk based on Container Linux would be tricky, because the disk contents could have changed after the initial creation -- perhaps Ubuntu is now on that disk and network helper will just work.

As far as the simple vs complex fields go, there are two flows for the Linode instance.  One where `config` and `disks` are used, and another where neither is used.

This is for parity with the Linode API's simple instance creation call, and simplicity for the majority of use cases.

The short answer, is to move the `authorized_users`, `image`, `root_pass` arguments from the `linode_instance` root into a `linode_instance` `disk {}`.  Then in that `linode_instance` also create a `config { devices { sda{} } }` to refer to the disk label managed by `disk {}`.

See "Simple Linode Instance" vs "Linode Instance with explicit Configs and Disks":
 
https://www.terraform.io/docs/providers/linode/r/instance.html#example-usage

And an example in the Linode docs:
https://www.linode.com/docs/applications/configuration-management/import-existing-infrastructure-to-terraform/#fill-in-your-linode-s-configuration-data

There is also an example here:
https://github.com/terraform-providers/terraform-provider-linode/blob/master/examples/main.tf#L130-L150

For an example of configuring Container Linux with private networking and hostname changes, see our [terraform-linode-k8s module](https://github.com/linode/terraform-linode-k8s/) (referring to a refactor PR here):

https://github.com/linode/terraform-linode-k8s/blob/393ec016ad6afd6fad67fabff85e32c73aa72b64/modules/instances/main.tf#L46

https://github.com/linode/terraform-linode-k8s/blob/393ec016ad6afd6fad67fabff85e32c73aa72b64/modules/instances/scripts/linode-network.sh

**Comment by gerhard** [comment]
We are in agreement on all points, thank you for all the great tips, this definitely helps.
